### self configurations #####
# eureka server instance name  
spring:
  application:
    name: registry-server-eureka
    
# eureka server port for standalone configuration   
server:
  port: 8761

# eureka.instance.hostname is not required for single host
eureka:
  datacenter: MY-DC
  environment: TEST
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    eviction-interval-timer-in-ms: 120000

### eureka server management endpoint /manage only
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: env,metrics,loggers,heapdump,httptrace,logfile,health
  #end point cache time out       
  endpoint:
    metrics:
      cache:
        time-to-live:10s
    httptrace:
      cache:
        time-to-live:10s
    env:
      cache:
        time-to-live:10s
    heapdump:
      cache:
        time-to-live:10s
    logfile:
      cache:
        time-to-live:10s
    health:
      cache:
        time-to-live:10s